### ISSUE TITLE
conflict between libraries (multiple definitions)

### ISSUE THREAD

**Issue by elgui** [spascual90/Fenix#1]
I'm using the provided versions of external librairies, and the build fails due to "multiple definition" of many sorts.
I have read that it comes from conflicting librairies, using the same interupt pin or timer.

```
Disabling relaxation: it will not work with multiple definitions
make: *** [makefile:93: Fenix.elf] Error 1
multiple definition of `__vector_25'
multiple definition of `__vector_26'
multiple definition of `__vector_36'
multiple definition of `__vector_37'
multiple definition of `__vector_51'
multiple definition of `__vector_52'
multiple definition of `__vector_54'
multiple definition of `__vector_55'
multiple definition of `NeoHWSerial::available()'
multiple definition of `NeoHWSerial::begin(unsigned long, unsigned char)'
multiple definition of `NeoHWSerial::end()'
multiple definition of `NeoHWSerial::flush()'
multiple definition of `NeoHWSerial::peek()'
multiple definition of `NeoHWSerial::read()'
multiple definition of `NeoHWSerial::write(unsigned char)'
multiple definition of `NeoSerial'
multiple definition of `NeoSerial1'
multiple definition of `NeoSerial2'
multiple definition of `NeoSerial3'
```

**Comment by spascual90** [comment]
Hello, difficult to analyze as I am on holidays, no access to my test platform... sorry.
I think this is related to wrong configuration of the library path folders.
Are you using Eclipse or the Arsuino IDE?
If you give more info related to this topic I may help for troubleshooting.

Regards
Sergio

**Comment by elgui** [comment]
Hello Sergio,
thank you for answering while being in vacations !
Following your  hint, I found the problem : I had duplicate NeoHWSerial files...
I have struggled so much to setup that workspace that it endep-up a bit messy.. But now it works, and as a developer, I'm super happy to further participate in that project !
I keep you posted, enjoy your holidays =)
PS: I am anchored in the South-West of Andalucia (just in case)
